"""Sync source photo folders -> web images + data.js, keeping every title/tag/description you've already written.

Run from anywhere:  python tools/sync.py
Safe to re-run: existing entries are never overwritten, new photos are inserted at random positions.
Photos deleted in tag.html: web copies removed, originals moved to _archive/ (restore = move back + remove id from deletedIds).
Originals deleted in Explorer: dropped from the site too (over 25 at once needs --yes, as a safety check).
"""
import hashlib, json, os, random, shutil, sys
from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARCHIVE = os.path.join(ROOT, "_archive")  # originals of deleted photos land here (gitignored, never auto-deleted)
SOURCES = [("Fully", "Fully Images"), ("Trillium Pacific", "TPM images")]
DATA = os.path.join(ROOT, "data.js")
THUMB, FULL = os.path.join(ROOT, "images", "thumb"), os.path.join(ROOT, "images", "full")
EXT = (".jpg", ".jpeg", ".png")  # ponytail: GIFs skipped (animated banners), add if you want them as stills

# Starting-point Item Type per source folder. Only used for photos seen for the first time.
FOLDER_TYPE = {
    "Above Desk Power": "Power & Cable", "Power Grommet": "Power & Cable", "Cable Management Trays": "Power & Cable",
    "Aleris Lamp": "Lighting", "Beam Lamps": "Lighting",
    "Bamboo Drawer": "Storage", "Desk Drawer": "Storage", "Sidekick": "Storage",
    "Colbe Shelves": "Shelving", "Desk Shelf": "Shelving",
    "Boden Desk": "Desk", "Jarvis": "Desk", "Nolan": "Desk", "Remi": "Desk",
    "Cooper Converter": "Desk Converter", "Cora Converter": "Desk Converter",
    "Colbe Tables": "Table", "Jarvis Conference Table": "Table", "Coffee Table": "Table",
    "Jarvis Benching System": "Workplace", "Haven Booth": "Workplace",
    "Fully Footrest": "Desk Accessory", "Jax Monitor Arms": "Desk Accessory", "Keyboard Trays": "Desk Accessory",
    "Jarvis touch Handsets": "Controls",
    "Kneeling Chairs": "Seating", "Luna Stool": "Seating", "Tic Toc": "Seating",
    "Architectural Installations": "Architectural", "Architectural Millwork": "Millwork",
    "Awards & Plaques": "Awards", "Branded Promo Items": "Promo Items",
    "Cutting Boards & Cheese Boards": "Cutting Boards", "Mass Timber Conference": "Event Display",
    "Shop & Tooling": "Tooling", "Signs": "Signage",
}


def load():
    """Return (items, deleted_ids). deletedIds = photos removed in tag.html, never re-added."""
    if not os.path.exists(DATA):
        return [], []
    s = open(DATA, encoding="utf-8").read()
    deleted = []
    for line in s.splitlines():
        if line.startswith("const deletedIds = "):
            deleted = json.loads(line[len("const deletedIds = "):].rstrip(";"))
    start = s.index("const portfolioData = ") + len("const portfolioData = ")
    return json.loads(s[start : s.rindex("]") + 1]), deleted


def save(items, deleted):
    body = ",\n".join(json.dumps(d, ensure_ascii=False, separators=(",", ":")) for d in items)  # same as JSON.stringify in tag.html
    tmp = DATA + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/sync.py and edited by tag.html. One item per line, array order = site order.\n")
        f.write(f"const deletedIds = {json.dumps(sorted(deleted), separators=(',', ':'))};\n")
        f.write(f"const portfolioData = [\n{body}\n];\n")
    os.replace(tmp, DATA)  # atomic: a crash mid-write can't truncate your tags


def scan():
    """Yield (company, top_folder, relative_path) for every source image, in stable order."""
    for company, top in SOURCES:
        base = os.path.join(ROOT, top)
        for dp, dirs, fs in os.walk(base):
            dirs.sort()
            for f in sorted(fs):
                if f.lower().endswith(EXT):
                    rel = os.path.relpath(os.path.join(dp, f), ROOT).replace("\\", "/")
                    yield company, os.path.relpath(dp, base).replace("\\", "/").split("/")[0], rel


def archive(rel):
    """Move a source file to _archive/<same path>. Never overwrites; never deletes."""
    dst = os.path.join(ARCHIVE, rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    base, ext = os.path.splitext(dst)
    n = 1
    while os.path.exists(dst):
        dst = f"{base} ({n}){ext}"
        n += 1
    shutil.move(os.path.join(ROOT, rel), dst)


def render(src, id_):
    """Write thumb + full JPEGs, return oriented (w, h)."""
    im = ImageOps.exif_transpose(Image.open(src))
    if im.mode in ("RGBA", "LA", "P"):  # flatten transparent product PNGs onto white
        im = im.convert("RGBA")
        bg = Image.new("RGB", im.size, "white")
        bg.paste(im, mask=im.split()[3])
        im = bg
    im = im.convert("RGB")
    w, h = im.size
    for folder, edge, q in ((FULL, 2000, 82), (THUMB, 800, 78)):
        out = im.copy()
        out.thumbnail((edge, edge), Image.LANCZOS)
        out.save(os.path.join(folder, id_ + ".jpg"), "JPEG", quality=q, optimize=True, progressive=True)
    return w, h


def purge(id_):
    """Remove a photo's web copies. Returns True if the full-size copy existed."""
    had = os.path.exists(os.path.join(FULL, id_ + ".jpg"))
    for folder in (THUMB, FULL):
        path = os.path.join(folder, id_ + ".jpg")
        if os.path.exists(path):
            os.remove(path)
    return had


def main():
    for _, top in SOURCES:  # a renamed/missing source folder must not look like "every photo was deleted"
        if not os.path.isdir(os.path.join(ROOT, top)):
            sys.exit(f"Source folder '{top}' not found. Nothing changed. Rename it back (or fix SOURCES) and re-run.")
    os.makedirs(THUMB, exist_ok=True)
    os.makedirs(FULL, exist_ok=True)
    items, deleted = load()
    gone = set(deleted)
    purged = sum(purge(id_) for id_ in gone)  # remove web copies of deleted photos so they never get published
    items = [d for d in items if d["id"] not in gone]
    by_id = {d["id"]: d for d in items}
    seen, added, dupes, archived = set(), 0, 0, 0
    for company, folder, rel in list(scan()):  # list(): we may move files while iterating
        # ID = content hash: renaming or moving a file keeps its tags, exact duplicates collapse to one item.
        id_ = hashlib.sha1(open(os.path.join(ROOT, rel), "rb").read()).hexdigest()[:12]
        if id_ in gone:  # deleted in tag.html: move the original (and any duplicate copies) to _archive/
            archive(rel)
            archived += 1
            continue
        if id_ in seen:
            dupes += 1
            continue
        seen.add(id_)
        if id_ in by_id:
            by_id[id_]["source"] = rel  # follow moves/renames, touch nothing else
            continue
        try:
            w, h = render(os.path.join(ROOT, rel), id_)
        except Exception as e:  # one corrupt file shouldn't stop the run
            print(f"  skip {rel}: {e}", file=sys.stderr)
            continue
        entry = {
            "id": id_, "imageSrc": f"images/full/{id_}.jpg", "title": folder, "company": company, "description": "",
            "tags": {"process": [], "material": [], "itemType": [FOLDER_TYPE.get(folder, folder)]},
            "w": w, "h": h, "hidden": False, "source": rel,
        }
        items.insert(random.randrange(len(items) + 1), entry)  # mixed, not by date or folder
        by_id[id_] = entry
        added += 1
        if added % 50 == 0:
            print(f"  {added} new...")
            save(items, deleted)  # checkpoint so a long first run can be interrupted and resumed
    # Originals deleted in Explorer: treat as deleted in tag.html (drop from the site, remember the id).
    missing = [d for d in items if d["id"] not in seen]
    removed_by_explorer = 0
    if len(missing) > 25 and "--yes" not in sys.argv:
        print(f"\n{len(missing)} photos have no original file any more, e.g.:", *[f"  {d['source']}" for d in missing[:5]],
              "Kept them for now (safety check). If you really deleted them, re-run:  python tools/sync.py --yes\n", sep="\n")
    else:
        for d in missing:
            deleted.append(d["id"])
            purge(d["id"])
            print(f"  removed (original deleted): {d['source']}")
        items = [d for d in items if d["id"] in seen]
        removed_by_explorer = len(missing)
    save(items, deleted)
    print(f"{len(items)} items | {added} new | {len(set(deleted))} deleted ({purged} web copies removed, {archived} originals "
          f"moved to _archive/, {removed_by_explorer} removed because the original was deleted) | {dupes} exact duplicates skipped")


if __name__ == "__main__":
    main()
